import { MacroCategoryType } from '../enums';
import { DeviceConfig } from './device-config.model';

/**
 * Row shape returned by `GET /api/devices` for the Back Office fleet table.
 *
 * `branchName` is denormalized server-side so the UI does not join against
 * the branches signal on every render. `lastSeenAt` is `null` for devices
 * that have never sent a heartbeat since being registered.
 */
export interface DeviceListItem {
  id: number;
  deviceUuid: string;
  name: string;
  mode: DeviceConfig['mode'];
  isActive: boolean;
  branchId: number;
  branchName: string;
  /** ISO date string; `null` when the device has never heartbeated */
  lastSeenAt: string | null;
  /** ISO date string of first registration */
  createdAt: string;
}

/** Payload accepted by `PATCH /api/devices/{id}`. */
export interface UpdateDevicePayload {
  name: string;
  branchId: number;
}

/** Response from `PATCH /api/devices/{id}/toggle-active`. */
export interface ToggleActiveResponse {
  id: number;
  isActive: boolean;
}

/** Request body for `POST /api/device/generate-code`. */
export interface GenerateCodePayload {
  branchId: number;
  mode: DeviceConfig['mode'];
  name: string;
}

/**
 * Response from `POST /api/device/generate-code`. Returns the freshly
 * minted 6-digit code together with the metadata the admin pre-configured
 * so the UI can render the success card without re-reading the form
 * (which is reset right after a successful generation).
 */
export interface GenerateCodeResponse {
  code: string;
  name: string;
  mode: DeviceConfig['mode'];
  branchName: string;
  /** ISO date string — when the code was issued */
  createdAt: string;
  /** ISO date string — when the code stops being valid (24 h window) */
  expiresAt: string;
}

/**
 * Row shape returned by `GET /api/device/pending-codes`. Lists every
 * activation code that has been issued but not yet redeemed by a device,
 * letting the admin verify which pairings are still in flight.
 */
export interface PendingDeviceCodeDto {
  code: string;
  name: string;
  mode: DeviceConfig['mode'];
  branchId: number;
  branchName: string;
  /** ISO date string — when the code was issued */
  createdAt: string;
  /** ISO date string — when the code stops being valid */
  expiresAt: string;
}

/** Request body for `POST /api/device/activate`. */
export interface ActivateDevicePayload {
  /** 6-digit pairing code issued from `/admin/devices` */
  code: string;
  /** Stable per-browser UUID generated by `DeviceService` */
  deviceUuid: string;
}

/**
 * Response from `POST /api/device/activate`.
 *
 * The endpoint is atomic: a single call validates the pairing code,
 * provisions the device server-side, and returns both the persistent
 * identity (`id`, `deviceUuid`) and the long-lived device JWT
 * (`deviceToken`) — no follow-up `/devices/register` call is required.
 *
 * The vertical-hint fields (`primaryMacroCategoryId`, `hasKitchen`,
 * `hasTables`) are optional for backwards compatibility with backends
 * that pre-date the enrichment.
 */
export interface ActivateDeviceResponse {
  id: number;
  deviceUuid: string;
  /** Long-lived device JWT — persisted by `DeviceService.saveDeviceToken` */
  deviceToken: string;
  /** Custom device name pre-configured by the admin when issuing the code */
  name: string;
  mode: DeviceConfig['mode'];
  branchId: number;
  branchName: string;
  businessId: number;
  businessName: string;
  primaryMacroCategoryId?: MacroCategoryType;
  hasKitchen?: boolean;
  hasTables?: boolean;
}
