import { MacroCategoryType } from '../enums';
import { DeviceConfig } from './device-config.model';

/**
 * Row shape returned by `GET /api/devices` for the Back Office fleet table.
 *
 * `branchName` is denormalized server-side so the UI does not join against
 * the branches signal on every render. `lastSeenAt` is `null` for devices
 * that have never sent a heartbeat since being registered.
 *
 * Note: `mode` may include `'bridge'` (Fino Bridge headless Windows service)
 * in addition to the Angular UI modes — bridges appear in the fleet table
 * once activated server-side by the native service.
 */
export interface DeviceListItem {
  id: number;
  deviceUuid: string;
  name: string;
  mode: DeviceConfig['mode'] | 'bridge';
  isActive: boolean;
  branchId: number;
  branchName: string;
  /** ISO date string; `null` when the device has never heartbeated */
  lastSeenAt: string | null;
  /** ISO date string of first registration */
  createdAt: string;
}

/** Payload accepted by `PATCH /api/devices/{id}`. */
export interface UpdateDevicePayload {
  name: string;
  branchId: number;
}

/** Response from `PATCH /api/devices/{id}/toggle-active`. */
export interface ToggleActiveResponse {
  id: number;
  isActive: boolean;
}

/**
 * Request body for `POST /api/device/generate-code`.
 *
 * `cashRegisterId` is optional — when present, the backend auto-links the
 * activated device to the specified cash register on redemption, so the
 * admin completes provisioning + register binding in a single trip
 * instead of two screens. Only meaningful when `mode === 'cashier'`; the
 * UI hides the field for other modes.
 *
 * Note: `mode` may include `'bridge'` (Fino Bridge headless Windows service);
 * the resulting code is redeemed by the native service, never by Angular.
 */
export interface GenerateCodePayload {
  branchId: number;
  mode: DeviceConfig['mode'] | 'bridge';
  name: string;
  cashRegisterId?: number;
}

/**
 * Response from `POST /api/device/generate-code`. Returns the freshly
 * minted 6-character alphanumeric code (secure alphabet
 * `[A-HJKMNP-TV-Z2-9]`, ambiguous chars excluded) together with the
 * metadata the admin pre-configured so the UI can render the success card
 * without re-reading the form (which is reset right after a successful
 * generation).
 *
 * Note: `mode` may include `'bridge'` (Fino Bridge headless Windows service)
 * — the success card shows the same code/branch/name metadata regardless.
 */
export interface GenerateCodeResponse {
  code: string;
  name: string;
  mode: DeviceConfig['mode'] | 'bridge';
  branchName: string;
  /** ISO date string — when the code was issued */
  createdAt: string;
  /** ISO date string — when the code stops being valid (24 h window) */
  expiresAt: string;
}

/**
 * Row shape returned by `GET /api/device/pending-codes`. Lists every
 * activation code that has been issued but not yet redeemed by a device,
 * letting the admin verify which pairings are still in flight.
 *
 * Note: `mode` may include `'bridge'` (Fino Bridge headless Windows service)
 * — pending bridge codes show up here until the native service redeems them.
 */
export interface PendingDeviceCodeDto {
  code: string;
  name: string;
  mode: DeviceConfig['mode'] | 'bridge';
  branchId: number;
  branchName: string;
  /** ISO date string — when the code was issued */
  createdAt: string;
  /** ISO date string — when the code stops being valid */
  expiresAt: string;
}

/** Request body for `POST /api/device/activate`. */
export interface ActivateDevicePayload {
  /** 6-character alphanumeric pairing code issued from `/admin/devices` */
  code: string;
  /** Stable per-browser UUID generated by `DeviceService` */
  deviceUuid: string;
}

/**
 * Response from `POST /api/device/activate`.
 *
 * The endpoint is atomic: a single call validates the pairing code,
 * provisions the device server-side, and returns both the persistent
 * identity (`id`, `deviceUuid`) and the long-lived device JWT
 * (`deviceToken`) — no follow-up `/devices/register` call is required.
 *
 * The vertical-hint fields (`primaryMacroCategoryId`, `hasKitchen`,
 * `hasTables`) are optional for backwards compatibility with backends
 * that pre-date the enrichment.
 */
export interface ActivateDeviceResponse {
  id: number;
  deviceUuid: string;
  /** Long-lived device JWT — persisted by `DeviceService.saveDeviceToken` */
  deviceToken: string;
  /** Custom device name pre-configured by the admin when issuing the code */
  name: string;
  /**
   * Note: intentionally narrow. Angular clients only activate UI modes.
   * 'bridge' codes are redeemed by the native Windows service downstream,
   * never by this Angular application.
   */
  mode: DeviceConfig['mode'];
  branchId: number;
  branchName: string;
  businessId: number;
  businessName: string;
  primaryMacroCategoryId?: MacroCategoryType;
  hasKitchen?: boolean;
  hasTables?: boolean;
}

/**
 * Per-mode quota row inside `DeviceLimitsDto.modes`.
 *
 * `usage` counts ACTIVE devices (revoked devices do not consume seats)
 * plus any pending activation codes that have not yet been redeemed —
 * the backend includes both so the UI cannot accidentally double-issue.
 *
 * `effectiveLimit` is the resolved cap for the tenant's plan + branch
 * combination. When `isUnlimited` is true the value should be ignored
 * by the UI (`Infinity` is rendered as the `∞` glyph instead).
 *
 * Note: `mode` may include `'bridge'` (Fino Bridge headless Windows service);
 * the backend emits `isUnlimited: true` for it on every plan since the
 * Bridge is treated as Core Infrastructure.
 */
export interface DeviceModeQuotaDto {
  mode: DeviceConfig['mode'] | 'bridge';
  usage: number;
  effectiveLimit: number;
  isLimitReached: boolean;
  isUnlimited: boolean;
}

/**
 * Response from `GET /api/Devices/limits?branchId={id}`.
 *
 * Backend returns ALL modes the tenant could possibly use (the modes
 * array length depends on plan + macro category). The UI looks up the
 * currently-selected mode via `.find(m => m.mode === selectedMode)`
 * and gracefully shows nothing when the mode is missing — meaning the
 * tenant cannot generate codes for that mode at all on their plan.
 */
export interface DeviceLimitsDto {
  modes: DeviceModeQuotaDto[];
}
